import pandas as pd
import pdb
import pandas as pd
from pathlib import Path
queue = ['queue_countpassed5', 'queue_countpassed10',
       'queue_countpassed15', 'queue_countpassed20', 'queue_countpassed25',
       'queue_countpassed30', 'queue_countpassed35', 'queue_countpassed40',
       'queue_countpassed60', 'queue_countpassed90', 'queue_countpassed120',
       'queue_countpassed3h', 'queue_countpassed4h', 'queue_countpassed5h',
       'queue_countpassed6h', 'queue_countpassed7h', 'queue_countpassed8h',
       'queue_countpassed9h', 'queue_countpassed10h', 'queue_countpassed11h',
       'queue_countpassed12h', 'queue_countpassed13h', 'queue_countpassed14h',
       'queue_countpassed15h', 'queue_countpassed16h', 'queue_countpassed17h',
       'queue_countpassed18h', 'queue_countpassed19h', 'queue_countpassed20h',
       'queue_countpassed21h', 'queue_countpassed22h', 'queue_countpassed23h',
       'queue_countpassed24h', 'queue_maxpassed5', 'queue_maxpassed10',
       'queue_maxpassed15', 'queue_maxpassed20', 'queue_maxpassed25',
       'queue_maxpassed30', 'queue_maxpassed35', 'queue_maxpassed40',
       'queue_maxpassed60', 'queue_maxpassed90', 'queue_maxpassed120',
       'queue_maxpassed3h', 'queue_maxpassed4h', 'queue_maxpassed5h',
       'queue_maxpassed6h', 'queue_maxpassed7h', 'queue_maxpassed8h',
       'queue_maxpassed9h', 'queue_maxpassed10h', 'queue_maxpassed11h',
       'queue_maxpassed12h', 'queue_maxpassed13h', 'queue_maxpassed14h',
       'queue_maxpassed15h', 'queue_maxpassed16h', 'queue_maxpassed17h',
       'queue_maxpassed18h', 'queue_maxpassed19h', 'queue_maxpassed20h',
       'queue_maxpassed21h', 'queue_maxpassed22h', 'queue_maxpassed23h',
       'queue_maxpassed24h', 'queue_minpassed5', 'queue_minpassed10',
       'queue_minpassed15', 'queue_minpassed20', 'queue_minpassed25',
       'queue_minpassed30', 'queue_minpassed35', 'queue_minpassed40',
       'queue_minpassed60', 'queue_minpassed90', 'queue_minpassed120',
       'queue_minpassed3h', 'queue_minpassed4h', 'queue_minpassed5h',
       'queue_minpassed6h', 'queue_minpassed7h', 'queue_minpassed8h',
       'queue_minpassed9h', 'queue_minpassed10h', 'queue_minpassed11h',
       'queue_minpassed12h', 'queue_minpassed13h', 'queue_minpassed14h',
       'queue_minpassed15h', 'queue_minpassed16h', 'queue_minpassed17h',
       'queue_minpassed18h', 'queue_minpassed19h', 'queue_minpassed20h',
       'queue_minpassed21h', 'queue_minpassed22h', 'queue_minpassed23h',
       'queue_minpassed24h', 'count_passed5', 'count_passed10',
       'count_passed15', 'count_passed20', 'count_passed25', 'count_passed30',
       'count_passed35', 'count_passed40', 'count_passed60', 'count_passed90',
       'count_passed120', 'count_passed3h', 'count_passed4h', 'count_passed5h',
       'count_passed6h', 'count_passed7h', 'count_passed8h', 'count_passed9h',
       'count_passed10h', 'count_passed11h', 'count_passed12h',
       'count_passed13h', 'count_passed14h', 'count_passed15h',
       'count_passed16h', 'count_passed17h', 'count_passed18h',
       'count_passed19h', 'count_passed20h', 'count_passed21h',
       'count_passed22h', 'count_passed23h', 'count_passed24h', 'wait_passed5',
       'wait_passed10', 'wait_passed15', 'wait_passed20', 'wait_passed25',
       'wait_passed30', 'wait_passed35', 'wait_passed40', 'wait_max5',
       'wait_max10', 'wait_max15', 'wait_max20', 'wait_max25', 'wait_max30',
       'wait_max35', 'wait_max40', 'wait_max60', 'wait_max90', 'wait_max120',
       'wait_max3h', 'wait_max4h', 'wait_max5h', 'wait_max6h', 'wait_max7h',
       'wait_max8h', 'wait_max9h', 'wait_max10h', 'wait_max11h', 'wait_max12h',
       'wait_max13h', 'wait_max14h', 'wait_max15h', 'wait_max16h',
       'wait_max17h', 'wait_max18h', 'wait_max19h', 'wait_max20h',
       'wait_max21h', 'wait_max22h', 'wait_max23h', 'wait_max24h', 'wait_min5',
       'wait_min10', 'wait_min15', 'wait_min20', 'wait_min25', 'wait_min30',
       'wait_min35', 'wait_min40', 'wait_min60', 'wait_min90', 'wait_min120',
       'wait_min3h', 'wait_min4h', 'wait_min5h', 'wait_min6h', 'wait_min7h',
       'wait_min8h', 'wait_min9h', 'wait_min10h', 'wait_min11h', 'wait_min12h',
       'wait_min13h', 'wait_min14h', 'wait_min15h', 'wait_min16h',
       'wait_min17h', 'wait_min18h', 'wait_min19h', 'wait_min20h',
       'wait_min21h', 'wait_min22h', 'wait_min23h', 'wait_min24h', 'wait_avr5',
       'wait_avr10', 'wait_avr15', 'wait_avr20', 'wait_avr25', 'wait_avr30',
       'wait_avr35', 'wait_avr40', 'wait_avr60', 'wait_avr90', 'wait_avr120',
       'wait_avr3h', 'wait_avr4h', 'wait_avr5h', 'wait_avr6h', 'wait_avr7h',
       'wait_avr8h', 'wait_avr9h', 'wait_avr10h', 'wait_avr11h', 'wait_avr12h',
       'wait_avr13h', 'wait_avr14h', 'wait_avr15h', 'wait_avr16h',
       'wait_avr17h', 'wait_avr18h', 'wait_avr19h', 'wait_avr20h',
       'wait_avr21h', 'wait_avr22h', 'wait_avr23h', 'wait_avr24h'
]
check = ['check_countpassed5', 'check_countpassed10', 'check_countpassed15',
       'check_countpassed20', 'check_countpassed25', 'check_countpassed30',
       'check_countpassed35', 'check_countpassed40', 'check_countpassed60',
       'check_countpassed90', 'check_countpassed120', 'check_countpassed3h',
       'check_countpassed4h', 'check_countpassed5h', 'check_countpassed6h',
       'check_countpassed7h', 'check_countpassed8h', 'check_countpassed9h',
       'check_countpassed10h', 'check_countpassed11h', 'check_countpassed12h',
       'check_countpassed13h', 'check_countpassed14h', 'check_countpassed15h',
       'check_countpassed16h', 'check_countpassed17h', 'check_countpassed18h',
       'check_countpassed19h', 'check_countpassed20h', 'check_countpassed21h',
       'check_countpassed22h', 'check_countpassed23h', 'check_countpassed24h',
       'check_T2passed5', 'check_T2passed10', 'check_T2passed15',
       'check_T2passed20', 'check_T2passed25', 'check_T2passed30',
       'check_T2passed35', 'check_T2passed40', 'check_T2passed60',
       'check_T2passed90', 'check_T2passed120', 'check_T2passed3h',
       'check_T2passed4h', 'check_T2passed5h', 'check_T2passed6h',
       'check_T2passed7h', 'check_T2passed8h', 'check_T2passed9h',
       'check_T2passed10h', 'check_T2passed11h', 'check_T2passed12h',
       'check_T2passed13h', 'check_T2passed14h', 'check_T2passed15h',
       'check_T2passed16h', 'check_T2passed17h', 'check_T2passed18h',
       'check_T2passed19h', 'check_T2passed20h', 'check_T2passed21h',
       'check_T2passed22h', 'check_T2passed23h', 'check_T2passed24h',
       'check_T3passed5', 'check_T3passed10', 'check_T3passed15',
       'check_T3passed20', 'check_T3passed25', 'check_T3passed30',
       'check_T3passed35', 'check_T3passed40', 'check_T3passed60',
       'check_T3passed90', 'check_T3passed120', 'check_T3passed3h',
       'check_T3passed4h', 'check_T3passed5h', 'check_T3passed6h',
       'check_T3passed7h', 'check_T3passed8h', 'check_T3passed9h',
       'check_T3passed10h', 'check_T3passed11h', 'check_T3passed12h',
       'check_T3passed13h', 'check_T3passed14h', 'check_T3passed15h',
       'check_T3passed16h', 'check_T3passed17h', 'check_T3passed18h',
       'check_T3passed19h', 'check_T3passed20h', 'check_T3passed21h',
       'check_T3passed22h', 'check_T3passed23h', 'check_T3passed24h',
       'check_manpassed5', 'check_manpassed10', 'check_manpassed15',
       'check_manpassed20', 'check_manpassed25', 'check_manpassed30',
       'check_manpassed35', 'check_manpassed40', 'check_manpassed60',
       'check_manpassed90', 'check_manpassed120', 'check_manpassed3h',
       'check_manpassed4h', 'check_manpassed5h', 'check_manpassed6h',
       'check_manpassed7h', 'check_manpassed8h', 'check_manpassed9h',
       'check_manpassed10h', 'check_manpassed11h', 'check_manpassed12h',
       'check_manpassed13h', 'check_manpassed14h', 'check_manpassed15h',
       'check_manpassed16h', 'check_manpassed17h', 'check_manpassed18h',
       'check_manpassed19h', 'check_manpassed20h', 'check_manpassed21h',
       'check_manpassed22h', 'check_manpassed23h', 'check_manpassed24h',
       'check_womanpassed5', 'check_womanpassed10', 'check_womanpassed15',
       'check_womanpassed20', 'check_womanpassed25', 'check_womanpassed30',
       'check_womanpassed35', 'check_womanpassed40', 'check_womanpassed60',
       'check_womanpassed90', 'check_womanpassed120', 'check_womanpassed3h',
       'check_womanpassed4h', 'check_womanpassed5h', 'check_womanpassed6h',
       'check_womanpassed7h', 'check_womanpassed8h', 'check_womanpassed9h',
       'check_womanpassed10h', 'check_womanpassed11h', 'check_womanpassed12h',
       'check_womanpassed13h', 'check_womanpassed14h', 'check_womanpassed15h',
       'check_womanpassed16h', 'check_womanpassed17h', 'check_womanpassed18h',
       'check_womanpassed19h', 'check_womanpassed20h', 'check_womanpassed21h',
       'check_womanpassed22h', 'check_womanpassed23h', 'check_womanpassed24h',
       'check_waitmax5', 'check_waitmax10', 'check_waitmax15',
       'check_waitmax20', 'check_waitmax25', 'check_waitmax30',
       'check_waitmax35', 'check_waitmax40', 'check_waitmax60',
       'check_waitmax90', 'check_waitmax120', 'check_waitmax3h',
       'check_waitmax4h', 'check_waitmax5h', 'check_waitmax6h',
       'check_waitmax7h', 'check_waitmax8h', 'check_waitmax9h',
       'check_waitmax10h', 'check_waitmax11h', 'check_waitmax12h',
       'check_waitmax13h', 'check_waitmax14h', 'check_waitmax15h',
       'check_waitmax16h', 'check_waitmax17h', 'check_waitmax18h',
       'check_waitmax19h', 'check_waitmax20h', 'check_waitmax21h',
       'check_waitmax22h', 'check_waitmax23h', 'check_waitmax24h',
       'check_waitmin5', 'check_waitmin10', 'check_waitmin15',
       'check_waitmin20', 'check_waitmin25', 'check_waitmin30',
       'check_waitmin35', 'check_waitmin40', 'check_waitmin60',
       'check_waitmin90', 'check_waitmin120', 'check_waitmin3h',
       'check_waitmin4h', 'check_waitmin5h', 'check_waitmin6h',
       'check_waitmin7h', 'check_waitmin8h', 'check_waitmin9h',
       'check_waitmin10h', 'check_waitmin11h', 'check_waitmin12h',
       'check_waitmin13h', 'check_waitmin14h', 'check_waitmin15h',
       'check_waitmin16h', 'check_waitmin17h', 'check_waitmin18h',
       'check_waitmin19h', 'check_waitmin20h', 'check_waitmin21h',
       'check_waitmin22h', 'check_waitmin23h', 'check_waitmin24h',
       'check_waitavr5', 'check_waitavr10', 'check_waitavr15',
       'check_waitavr20', 'check_waitavr25', 'check_waitavr30',
       'check_waitavr35', 'check_waitavr40', 'check_waitavr60',
       'check_waitavr90', 'check_waitavr120', 'check_waitavr3h',
       'check_waitavr4h', 'check_waitavr5h', 'check_waitavr6h',
       'check_waitavr7h', 'check_waitavr8h', 'check_waitavr9h',
       'check_waitavr10h', 'check_waitavr11h', 'check_waitavr12h',
       'check_waitavr13h', 'check_waitavr14h', 'check_waitavr15h',
       'check_waitavr16h', 'check_waitavr17h', 'check_waitavr18h',
       'check_waitavr19h', 'check_waitavr20h', 'check_waitavr21h',
       'check_waitavr22h', 'check_waitavr23h', 'check_waitavr24h']
traff = ['traff_t2enterpassed5', 'traff_t2enterpassed10',
       'traff_t2enterpassed15', 'traff_t2enterpassed20',
       'traff_t2enterpassed25', 'traff_t2enterpassed30',
       'traff_t2enterpassed35', 'traff_t2enterpassed40',
       'traff_t2enterpassed60', 'traff_t2enterpassed90',
       'traff_t2enterpassed120', 'traff_t2enterpassed3h',
       'traff_t2enterpassed4h', 'traff_t2enterpassed5h',
       'traff_t2enterpassed6h', 'traff_t2enterpassed7h',
       'traff_t2enterpassed8h', 'traff_t2enterpassed9h',
       'traff_t2enterpassed10h', 'traff_t2enterpassed11h',
       'traff_t2enterpassed12h', 'traff_t2enterpassed13h',
       'traff_t2enterpassed14h', 'traff_t2enterpassed15h',
       'traff_t2enterpassed16h', 'traff_t2enterpassed17h',
       'traff_t2enterpassed18h', 'traff_t2enterpassed19h',
       'traff_t2enterpassed20h', 'traff_t2enterpassed21h',
       'traff_t2enterpassed22h', 'traff_t2enterpassed23h',
       'traff_t2enterpassed24h', 'traff_t2exitpassed5', 'traff_t2exitpassed10',
       'traff_t2exitpassed15', 'traff_t2exitpassed20', 'traff_t2exitpassed25',
       'traff_t2exitpassed30', 'traff_t2exitpassed35', 'traff_t2exitpassed40',
       'traff_t2exitpassed60', 'traff_t2exitpassed90', 'traff_t2exitpassed120',
       'traff_t2exitpassed3h', 'traff_t2exitpassed4h', 'traff_t2exitpassed5h',
       'traff_t2exitpassed6h', 'traff_t2exitpassed7h', 'traff_t2exitpassed8h',
       'traff_t2exitpassed9h', 'traff_t2exitpassed10h',
       'traff_t2exitpassed11h', 'traff_t2exitpassed12h',
       'traff_t2exitpassed13h', 'traff_t2exitpassed14h',
       'traff_t2exitpassed15h', 'traff_t2exitpassed16h',
       'traff_t2exitpassed17h', 'traff_t2exitpassed18h',
       'traff_t2exitpassed19h', 'traff_t2exitpassed20h',
       'traff_t2exitpassed21h', 'traff_t2exitpassed22h',
       'traff_t2exitpassed23h', 'traff_t2exitpassed24h',
       'traff_t3enterpassed5', 'traff_t3enterpassed10',
       'traff_t3enterpassed15', 'traff_t3enterpassed20',
       'traff_t3enterpassed25', 'traff_t3enterpassed30',
       'traff_t3enterpassed35', 'traff_t3enterpassed40',
       'traff_t3enterpassed60', 'traff_t3enterpassed90',
       'traff_t3enterpassed120', 'traff_t3enterpassed3h',
       'traff_t3enterpassed4h', 'traff_t3enterpassed5h',
       'traff_t3enterpassed6h', 'traff_t3enterpassed7h',
       'traff_t3enterpassed8h', 'traff_t3enterpassed9h',
       'traff_t3enterpassed10h', 'traff_t3enterpassed11h',
       'traff_t3enterpassed12h', 'traff_t3enterpassed13h',
       'traff_t3enterpassed14h', 'traff_t3enterpassed15h',
       'traff_t3enterpassed16h', 'traff_t3enterpassed17h',
       'traff_t3enterpassed18h', 'traff_t3enterpassed19h',
       'traff_t3enterpassed20h', 'traff_t3enterpassed21h',
       'traff_t3enterpassed22h', 'traff_t3enterpassed23h',
       'traff_t3enterpassed24h', 'traff_t3exitpassed5', 'traff_t3exitpassed10',
       'traff_t3exitpassed15', 'traff_t3exitpassed20', 'traff_t3exitpassed25',
       'traff_t3exitpassed30', 'traff_t3exitpassed35', 'traff_t3exitpassed40',
       'traff_t3exitpassed60', 'traff_t3exitpassed90', 'traff_t3exitpassed120',
       'traff_t3exitpassed3h', 'traff_t3exitpassed4h', 'traff_t3exitpassed5h',
       'traff_t3exitpassed6h', 'traff_t3exitpassed7h', 'traff_t3exitpassed8h',
       'traff_t3exitpassed9h', 'traff_t3exitpassed10h',
       'traff_t3exitpassed11h', 'traff_t3exitpassed12h',
       'traff_t3exitpassed13h', 'traff_t3exitpassed14h',
       'traff_t3exitpassed15h', 'traff_t3exitpassed16h',
       'traff_t3exitpassed17h', 'traff_t3exitpassed18h',
       'traff_t3exitpassed19h', 'traff_t3exitpassed20h',
       'traff_t3exitpassed21h', 'traff_t3exitpassed22h',
       'traff_t3exitpassed23h', 'traff_t3exitpassed24h']
air = ['plane_in30',
       'plane_in60', 'plane_in90', 'plane_in120', 'plane_in3', 'plane_in4',
       'plane_in5', 'plane_in6', 'plane_in7', 'plane_in8', 'plane_in9',
       'plane_in10', 'plane_in11', 'plane_in12', 'plane_mix30', 'plane_mix60',
       'plane_mix90', 'plane_mix120', 'plane_mix3', 'plane_mix4', 'plane_mix5',
       'plane_mix6', 'plane_mix7', 'plane_mix8', 'plane_mix9', 'plane_mix10',
       'plane_mix11', 'plane_mix12', 'plane_t2_30', 'plane_t2_60',
       'plane_t2_90', 'plane_t2_120', 'plane_t2_3', 'plane_t2_4', 'plane_t2_5',
       'plane_t2_6', 'plane_t2_7', 'plane_t2_8', 'plane_t2_9', 'plane_t2_10',
       'plane_t2_11', 'plane_t2_12', 'plane_t3_30', 'plane_t3_60',
       'plane_t3_90', 'plane_t3_120', 'plane_t3_3', 'plane_t3_4', 'plane_t3_5',
       'plane_t3_6', 'plane_t3_7', 'plane_t3_8', 'plane_t3_9', 'plane_t3_10',
       'plane_t3_11', 'plane_t3_12', 'plane_num_30', 'plane_num_60',
       'plane_num_90', 'plane_num_120', 'plane_num_3', 'plane_num_4',
       'plane_num_5', 'plane_num_6', 'plane_num_7', 'plane_num_8',
       'plane_num_9', 'plane_num_10', 'plane_num_11', 'plane_num_12',
       'check_waitmax5', 'check_waitmax10', 'check_waitmax15',
       'check_waitmax20', 'check_waitmax25', 'check_waitmax30',
       'check_waitmax35', 'check_waitmax40', 'check_waitmax60',
       'check_waitmax90', 'check_waitmax120', 'check_waitmax3h',
       'check_waitmax4h', 'check_waitmax5h', 'check_waitmax6h',
       'check_waitmax7h', 'check_waitmax8h', 'check_waitmax9h',
       'check_waitmax10h', 'check_waitmax11h', 'check_waitmax12h',
       'check_waitmax13h', 'check_waitmax14h', 'check_waitmax15h',
       'check_waitmax16h', 'check_waitmax17h', 'check_waitmax18h',
       'check_waitmax19h', 'check_waitmax20h', 'check_waitmax21h',
       'check_waitmax22h', 'check_waitmax23h', 'check_waitmax24h',
       'check_waitmin5', 'check_waitmin10', 'check_waitmin15',
       'check_waitmin20', 'check_waitmin25', 'check_waitmin30',
       'check_waitmin35', 'check_waitmin40', 'check_waitmin60',
       'check_waitmin90', 'check_waitmin120', 'check_waitmin3h',
       'check_waitmin4h', 'check_waitmin5h', 'check_waitmin6h',
       'check_waitmin7h', 'check_waitmin8h', 'check_waitmin9h',
       'check_waitmin10h', 'check_waitmin11h', 'check_waitmin12h',
       'check_waitmin13h', 'check_waitmin14h', 'check_waitmin15h',
       'check_waitmin16h', 'check_waitmin17h', 'check_waitmin18h',
       'check_waitmin19h', 'check_waitmin20h', 'check_waitmin21h',
       'check_waitmin22h', 'check_waitmin23h', 'check_waitmin24h',
       'check_waitavr5', 'check_waitavr10', 'check_waitavr15',
       'check_waitavr20', 'check_waitavr25', 'check_waitavr30',
       'check_waitavr35', 'check_waitavr40', 'check_waitavr60',
       'check_waitavr90', 'check_waitavr120', 'check_waitavr3h',
       'check_waitavr4h', 'check_waitavr5h', 'check_waitavr6h',
       'check_waitavr7h', 'check_waitavr8h', 'check_waitavr9h',
       'check_waitavr10h', 'check_waitavr11h', 'check_waitavr12h',
       'check_waitavr13h', 'check_waitavr14h', 'check_waitavr15h',
       'check_waitavr16h', 'check_waitavr17h', 'check_waitavr18h',
       'check_waitavr19h', 'check_waitavr20h', 'check_waitavr21h',
       'check_waitavr22h', 'check_waitavr23h', 'check_waitavr24h'
       ]
fs = ['hurst',
       'series_length', 'unitroot_pp', 'unitroot_kpss', 'hw_alpha', 'hw_beta',
       'hw_gamma', 'stability', 'nperiods', 'seasonal_period', 'trend',
       'spike', 'linearity', 'curvature', 'e_acf1', 'e_acf10',
       'seasonal_strength', 'peak', 'trough', 'x_pacf5', 'diff1x_pacf5',
       'diff2x_pacf5', 'seas_pacf', 'nonlinearity', 'lumpiness', 'alpha',
       'beta', 'arch_acf', 'garch_acf', 'arch_r2', 'garch_r2', 'flat_spots',
       'entropy', 'crossing_points', 'arch_lm', 'x_acf1', 'x_acf10',
       'diff1_acf1', 'diff1_acf10', 'diff2_acf1', 'diff2_acf10', 'seas_acf1']
# 原始数据所在目录
base_dir = Path("/root/autodl-tmp/airport_project/data/xiao")

# 要处理的文件
data_files = ["train.csv", "test.csv"]

# 消融实验特征组
feature_groups = {
    "queue": queue,
    "check": check,
    "traff": traff,
    "air": air,
    "fs": fs
}

for group_name, drop_cols in feature_groups.items():
    print(f"\n========== 正在生成 {group_name} 消融数据 ==========")

    # 输出文件夹，例如 /data/xiao/queue
    out_dir = base_dir / group_name
    out_dir.mkdir(parents=True, exist_ok=True)

    for file_name in data_files:
        input_path = base_dir / file_name
        output_path = out_dir / file_name

        print(f"正在处理：{input_path}")

        df = pd.read_csv(input_path)

        # 只删除当前数据中真实存在的列，避免因为某些列不存在而报错
        existing_drop_cols = [col for col in drop_cols if col in df.columns]
        missing_cols = [col for col in drop_cols if col not in df.columns]

        df_ablation = df.drop(columns=existing_drop_cols)

        df_ablation.to_csv(output_path, index=False, encoding="utf-8-sig")

        print(f"原始列数：{df.shape[1]}")
        print(f"删除列数：{len(existing_drop_cols)}")
        print(f"剩余列数：{df_ablation.shape[1]}")
        print(f"保存到：{output_path}")

        if len(missing_cols) > 0:
            print(f"警告：{group_name} 中有 {len(missing_cols)} 个特征在 {file_name} 中不存在，已自动跳过。")